/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_PROTO_PROTO_FILES_MONITORING_PB_H_INCLUDED
#define PB_PROTO_PROTO_FILES_MONITORING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Monitoring_message_type {
    Monitoring_message_type_MSG_NONE = 0,
    Monitoring_message_type_MSG_TWR = 1,
    Monitoring_message_type_MSG_TDOA = 2
} Monitoring_message_type;

/* Struct definitions */
typedef struct _Monitoring_msg_TWR {
    Monitoring_message_type MessageType;
    uint32_t NN;
    float Distance;
    uint32_t Timestamp;
} Monitoring_msg_TWR;

typedef struct _Monitoring {
    bool has_TWR;
    Monitoring_msg_TWR TWR;
} Monitoring;


/* Helper constants for enums */
#define _Monitoring_message_type_MIN Monitoring_message_type_MSG_NONE
#define _Monitoring_message_type_MAX Monitoring_message_type_MSG_TDOA
#define _Monitoring_message_type_ARRAYSIZE ((Monitoring_message_type)(Monitoring_message_type_MSG_TDOA+1))


/* Initializer values for message structs */
#define Monitoring_init_default                  {false, Monitoring_msg_TWR_init_default}
#define Monitoring_msg_TWR_init_default          {_Monitoring_message_type_MIN, 0, 0, 0}
#define Monitoring_init_zero                     {false, Monitoring_msg_TWR_init_zero}
#define Monitoring_msg_TWR_init_zero             {_Monitoring_message_type_MIN, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Monitoring_msg_TWR_MessageType_tag       1
#define Monitoring_msg_TWR_NN_tag                2
#define Monitoring_msg_TWR_Distance_tag          3
#define Monitoring_msg_TWR_Timestamp_tag         4
#define Monitoring_TWR_tag                       1

/* Struct field encoding specification for nanopb */
#define Monitoring_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  TWR,               1)
#define Monitoring_CALLBACK NULL
#define Monitoring_DEFAULT NULL
#define Monitoring_TWR_MSGTYPE Monitoring_msg_TWR

#define Monitoring_msg_TWR_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    MessageType,       1) \
X(a, STATIC,   SINGULAR, UINT32,   NN,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    Distance,          3) \
X(a, STATIC,   SINGULAR, UINT32,   Timestamp,         4)
#define Monitoring_msg_TWR_CALLBACK NULL
#define Monitoring_msg_TWR_DEFAULT NULL

extern const pb_msgdesc_t Monitoring_msg;
extern const pb_msgdesc_t Monitoring_msg_TWR_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Monitoring_fields &Monitoring_msg
#define Monitoring_msg_TWR_fields &Monitoring_msg_TWR_msg

/* Maximum encoded size of messages (where known) */
#define Monitoring_size                          21
#define Monitoring_msg_TWR_size                  19

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
