# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Monitoring.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Monitoring.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10Monitoring.proto\"\xd2\x01\n\nMonitoring\x12 \n\x03TWR\x18\x01 \x01(\x0b\x32\x13.Monitoring.msg_TWR\x1ai\n\x07msg_TWR\x12-\n\x0bMessageType\x18\x01 \x01(\x0e\x32\x18.Monitoring.message_type\x12\n\n\x02NN\x18\x02 \x01(\r\x12\x10\n\x08\x44istance\x18\x03 \x01(\x02\x12\x11\n\tTimestamp\x18\x04 \x01(\r\"7\n\x0cmessage_type\x12\x0c\n\x08MSG_NONE\x10\x00\x12\x0b\n\x07MSG_TWR\x10\x01\x12\x0c\n\x08MSG_TDOA\x10\x02\x62\x06proto3'
)



_MONITORING_MESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='message_type',
  full_name='Monitoring.message_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MSG_NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TWR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TDOA', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=176,
  serialized_end=231,
)
_sym_db.RegisterEnumDescriptor(_MONITORING_MESSAGE_TYPE)


_MONITORING_MSG_TWR = _descriptor.Descriptor(
  name='msg_TWR',
  full_name='Monitoring.msg_TWR',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MessageType', full_name='Monitoring.msg_TWR.MessageType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NN', full_name='Monitoring.msg_TWR.NN', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Distance', full_name='Monitoring.msg_TWR.Distance', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='Monitoring.msg_TWR.Timestamp', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=174,
)

_MONITORING = _descriptor.Descriptor(
  name='Monitoring',
  full_name='Monitoring',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TWR', full_name='Monitoring.TWR', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MONITORING_MSG_TWR, ],
  enum_types=[
    _MONITORING_MESSAGE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=231,
)

_MONITORING_MSG_TWR.fields_by_name['MessageType'].enum_type = _MONITORING_MESSAGE_TYPE
_MONITORING_MSG_TWR.containing_type = _MONITORING
_MONITORING.fields_by_name['TWR'].message_type = _MONITORING_MSG_TWR
_MONITORING_MESSAGE_TYPE.containing_type = _MONITORING
DESCRIPTOR.message_types_by_name['Monitoring'] = _MONITORING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Monitoring = _reflection.GeneratedProtocolMessageType('Monitoring', (_message.Message,), {

  'msg_TWR' : _reflection.GeneratedProtocolMessageType('msg_TWR', (_message.Message,), {
    'DESCRIPTOR' : _MONITORING_MSG_TWR,
    '__module__' : 'Monitoring_pb2'
    # @@protoc_insertion_point(class_scope:Monitoring.msg_TWR)
    })
  ,
  'DESCRIPTOR' : _MONITORING,
  '__module__' : 'Monitoring_pb2'
  # @@protoc_insertion_point(class_scope:Monitoring)
  })
_sym_db.RegisterMessage(Monitoring)
_sym_db.RegisterMessage(Monitoring.msg_TWR)


# @@protoc_insertion_point(module_scope)
