# Generated by Django 2.1.7 on 2019-06-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('subnet_mask', models.CharField(max_length=16)),
                ('server_ip_address', models.CharField(max_length=16)),
                ('server_port', models.IntegerField()),
                ('notes', models.CharField(max_length=1024)),
            ],
        ),
    ]
