# Generated by Django 2.1.7 on 2019-07-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor',
            name='notes',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
