/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_PROTO_MONITORING_PB_H_INCLUDED
#define PB_PROTO_MONITORING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Monitoring_TWR_message {
    uint32_t NodeID;
    uint32_t InitiatorID;
    float Distance;
    uint32_t NodeTicks;
    uint32_t PollNN;
    uint32_t FinalNN;
    uint32_t ResponseNN;
} Monitoring_TWR_message;

typedef struct _Monitoring {
    bool has_TWR;
    Monitoring_TWR_message TWR;
} Monitoring;


/* Initializer values for message structs */
#define Monitoring_init_default                  {false, Monitoring_TWR_message_init_default}
#define Monitoring_TWR_message_init_default      {0, 0, 0, 0, 0, 0, 0}
#define Monitoring_init_zero                     {false, Monitoring_TWR_message_init_zero}
#define Monitoring_TWR_message_init_zero         {0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Monitoring_TWR_message_NodeID_tag        1
#define Monitoring_TWR_message_InitiatorID_tag   2
#define Monitoring_TWR_message_Distance_tag      3
#define Monitoring_TWR_message_NodeTicks_tag     4
#define Monitoring_TWR_message_PollNN_tag        5
#define Monitoring_TWR_message_ResponseNN_tag    7
#define Monitoring_TWR_message_FinalNN_tag       6
#define Monitoring_TWR_tag                       1

/* Struct field encoding specification for nanopb */
#define Monitoring_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  TWR,               1)
#define Monitoring_CALLBACK NULL
#define Monitoring_DEFAULT NULL
#define Monitoring_TWR_MSGTYPE Monitoring_TWR_message

#define Monitoring_TWR_message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   NodeID,            1) \
X(a, STATIC,   SINGULAR, UINT32,   InitiatorID,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    Distance,          3) \
X(a, STATIC,   SINGULAR, UINT32,   NodeTicks,         4) \
X(a, STATIC,   SINGULAR, UINT32,   PollNN,            5) \
X(a, STATIC,   SINGULAR, UINT32,   FinalNN,           6) \
X(a, STATIC,   SINGULAR, UINT32,   ResponseNN,        7)
#define Monitoring_TWR_message_CALLBACK NULL
#define Monitoring_TWR_message_DEFAULT NULL

extern const pb_msgdesc_t Monitoring_msg;
extern const pb_msgdesc_t Monitoring_TWR_message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Monitoring_fields &Monitoring_msg
#define Monitoring_TWR_message_fields &Monitoring_TWR_message_msg

/* Maximum encoded size of messages (where known) */
#define Monitoring_size                          43
#define Monitoring_TWR_message_size              41

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
