# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Monitoring.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Monitoring.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10Monitoring.proto\"\xc1\x01\n\nMonitoring\x12$\n\x03TWR\x18\x01 \x01(\x0b\x32\x17.Monitoring.TWR_message\x1a\x8c\x01\n\x0bTWR_message\x12\x0e\n\x06NodeID\x18\x01 \x01(\r\x12\x13\n\x0bInitiatorID\x18\x02 \x01(\r\x12\x10\n\x08\x44istance\x18\x03 \x01(\x02\x12\x11\n\tNodeTicks\x18\x04 \x01(\r\x12\x0e\n\x06PollNN\x18\x05 \x01(\r\x12\x12\n\nResponseNN\x18\x07 \x01(\r\x12\x0f\n\x07\x46inalNN\x18\x06 \x01(\rb\x06proto3'
)




_MONITORING_TWR_MESSAGE = _descriptor.Descriptor(
  name='TWR_message',
  full_name='Monitoring.TWR_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='NodeID', full_name='Monitoring.TWR_message.NodeID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='InitiatorID', full_name='Monitoring.TWR_message.InitiatorID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Distance', full_name='Monitoring.TWR_message.Distance', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NodeTicks', full_name='Monitoring.TWR_message.NodeTicks', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PollNN', full_name='Monitoring.TWR_message.PollNN', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ResponseNN', full_name='Monitoring.TWR_message.ResponseNN', index=5,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FinalNN', full_name='Monitoring.TWR_message.FinalNN', index=6,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=214,
)

_MONITORING = _descriptor.Descriptor(
  name='Monitoring',
  full_name='Monitoring',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TWR', full_name='Monitoring.TWR', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MONITORING_TWR_MESSAGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=214,
)

_MONITORING_TWR_MESSAGE.containing_type = _MONITORING
_MONITORING.fields_by_name['TWR'].message_type = _MONITORING_TWR_MESSAGE
DESCRIPTOR.message_types_by_name['Monitoring'] = _MONITORING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Monitoring = _reflection.GeneratedProtocolMessageType('Monitoring', (_message.Message,), {

  'TWR_message' : _reflection.GeneratedProtocolMessageType('TWR_message', (_message.Message,), {
    'DESCRIPTOR' : _MONITORING_TWR_MESSAGE,
    '__module__' : 'Monitoring_pb2'
    # @@protoc_insertion_point(class_scope:Monitoring.TWR_message)
    })
  ,
  'DESCRIPTOR' : _MONITORING,
  '__module__' : 'Monitoring_pb2'
  # @@protoc_insertion_point(class_scope:Monitoring)
  })
_sym_db.RegisterMessage(Monitoring)
_sym_db.RegisterMessage(Monitoring.TWR_message)


# @@protoc_insertion_point(module_scope)
