/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "Monitoring.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Monitoring, Monitoring, AUTO)


PB_BIND(Monitoring_TWR_message, Monitoring_TWR_message, AUTO)


PB_BIND(Monitoring_TDOA_message, Monitoring_TDOA_message, AUTO)



