#!/bin/bash
set -e

psql -a -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE root LOGIN PASSWORD 'root' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
    CREATE DATABASE core WITH ENCODING='UTF8' OWNER=root;
EOSQL
